name: movies_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  http: any
  provider: ^6.0.0
  video_player: any
  youtube_player_flutter: any
  flutter_rating_bar: ^4.0.0
  get_it: ^8.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/movies.png
    - assets/splash.png

  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf